apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: review-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: review-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
